import React from "react";
import { FaChartBar, FaFileInvoiceDollar, FaShoppingCart } from "react-icons/fa";
import "./Reports.css";

const Reports = () => {
  const reports = [
    { id: "R001", type: "Sales", date: "2025-02-26", total: "$5,000", generatedBy: "Admin" },
    { id: "R002", type: "Inventory", date: "2025-02-25", total: "$12,000", generatedBy: "Manager" },
    { id: "R003", type: "Orders", date: "2025-02-24", total: "$3,500", generatedBy: "Admin" },
    { id: "R004", type: "Returns", date: "2025-02-23", total: "$800", generatedBy: "Staff" },
  ];

  return (
    <div className="reports-container">
      <h2>Reports</h2>

      {/* Report Summary Cards */}
      <div className="report-summary">
        <div className="report-card sales">
          <FaChartBar className="report-icon" />
          <h3>Sales</h3>
          <p>$25,000</p>
        </div>
        <div className="report-card inventory">
          <FaFileInvoiceDollar className="report-icon" />
          <h3>Inventory Value</h3>
          <p>$50,000</p>
        </div>
        <div className="report-card orders">
          <FaShoppingCart className="report-icon" />
          <h3>Total Orders</h3>
          <p>1,200</p>
        </div>
      </div>

      {/* Report Table */}
      <table className="reports-table">
        <thead>
          <tr>
            <th>Report ID</th>
            <th>Type</th>
            <th>Date</th>
            <th>Total</th>
            <th>Generated By</th>
          </tr>
        </thead>
        <tbody>
          {reports.map((report) => (
            <tr key={report.id}>
              <td>{report.id}</td>
              <td>{report.type}</td>
              <td>{report.date}</td>
              <td>{report.total}</td>
              <td>{report.generatedBy}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Reports;
